/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.quanlytaphoa.View;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import com.quanlytaphoa.Model.Account;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import static java.io.File.separator;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class DangNhap extends javax.swing.JFrame {

    private Account ac;
    private static String CUR_DIR = System.getProperty("user.dir");

    public DangNhap() {
        
        initComponents();
        
        setLocationRelativeTo(null);
        setTitle("Login");
        //setPreferredSize(new Dimension(600, 900));
        this.setSize(600, 600);
    }
    
    // hàm kiểm tra user và password
    private void try2Login()
    {
        MainPage homePage = new MainPage();
        String user, pass;
        user = userTextField.getText();
        pass = new String(PasswordField.getPassword());
        boolean status = false;
        
        // kiểm tra user & password
        String filePath;
        //D:/Learning Java/QuanLyTapHoa_DoAnJava09/Manage Files/Account.json
        
        filePath = CUR_DIR + separator + "Manage Files" + separator + "Account.json";
        FileReader fr = null;
        try {
            // đọc file Account.json vào listAccount
            fr = new FileReader(filePath);
            java.lang.reflect.Type accountType = new TypeToken<Collection<Account>>(){}.getType();
            ArrayList<Account> listAccount = new ArrayList<>();
            Gson gson = new Gson();
            listAccount = gson.fromJson(fr, accountType);
            for (Account a: listAccount)
            {
                if (a.getUser().equals(user) && a.getPassword().equals(pass))
                {
                    status = true;
                    break;
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (status)
        {
            this.setVisible(false);
            homePage.setLocationRelativeTo(null);
            homePage.setSize(1100, 600);
            homePage.setPreferredSize(new Dimension(1100, 600));
            homePage.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this,
                    "WRRONG ACCOUNT!!!",
                    "FAIL TO LOGIN",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userTextField = new javax.swing.JTextField();
        userName_label = new javax.swing.JLabel();
        pass_Label = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        login_Button = new javax.swing.JButton();
        login_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setPreferredSize(new java.awt.Dimension(610, 450));
        getContentPane().setLayout(null);

        userTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userTextFieldKeyPressed(evt);
            }
        });
        getContentPane().add(userTextField);
        userTextField.setBounds(280, 410, 190, 30);

        userName_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userName_label.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\OneDrive\\Máy tính\\user_icon.png")); // NOI18N
        userName_label.setText("Username");
        userName_label.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        userName_label.setIconTextGap(10);
        getContentPane().add(userName_label);
        userName_label.setBounds(150, 320, 130, 50);

        pass_Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pass_Label.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\OneDrive\\Máy tính\\secrecy-icon.png")); // NOI18N
        pass_Label.setText("Password");
        pass_Label.setIconTextGap(20);
        getContentPane().add(pass_Label);
        pass_Label.setBounds(160, 390, 130, 60);

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        PasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordFieldKeyPressed(evt);
            }
        });
        getContentPane().add(PasswordField);
        PasswordField.setBounds(280, 330, 190, 30);

        login_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        login_Button.setText("Login");
        login_Button.setAlignmentX(1.0F);
        login_Button.setAlignmentY(1.0F);
        login_Button.setPreferredSize(new java.awt.Dimension(50, 23));
        login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_ButtonActionPerformed(evt);
            }
        });
        login_Button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_ButtonKeyPressed(evt);
            }
        });
        getContentPane().add(login_Button);
        login_Button.setBounds(442, 473, 110, 40);

        login_Label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        login_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_Label.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\OneDrive\\Máy tính\\logo (250_175).png")); // NOI18N
        getContentPane().add(login_Label);
        login_Label.setBounds(160, 30, 270, 290);
        login_Label.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_ButtonActionPerformed
        // TODO add your handling code here:
        try2Login();
    }//GEN-LAST:event_login_ButtonActionPerformed

    private void PasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try2Login();
        }
    }//GEN-LAST:event_PasswordFieldKeyPressed

    private void userTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userTextFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try2Login();
        }
    }//GEN-LAST:event_userTextFieldKeyPressed

    private void login_ButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_ButtonKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try2Login();
        }
    }//GEN-LAST:event_login_ButtonKeyPressed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton login_Button;
    private javax.swing.JLabel login_Label;
    private javax.swing.JLabel pass_Label;
    private javax.swing.JLabel userName_label;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables
}
